version: '2'
services:

  web:
    build: eBayApp/.
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: ebay_info
      MYSQL_USER: ebay
      MYSQL_PASSWORD: ebay

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin 
    environment: 
      PMA_ARBITRARY: 1 
      PMA_HOST: db
      PMA_PORT: 3306
    ports: 
      - "80:80"
    links:
      - db
    depends_on:
      - db
